name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          npm install 
          npm test
  JSDoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run JSDocs
        run: |
          npm install --save-dev jsdoc
          npx jsdoc “./Jest-UnitTests/subtraction.js”